[workspace]
edition = "2024"
rust-version = "1.90.0"
resolver = "2"
members = [
  "core",
  "desktop",
  "editor",
  "events",
  "glwn",
  "gl_window_context",
  "math",
  "wasm",
  "demos/desktop_demo",
  "demos/wasm_demo",
  "modules/inputs",
  "modules/kinematics",
  "modules/lighting",
]
