[package]
name = "core"
version = "0.0.1"
edition = "2024"
rust-version = "1.90.0"

[dependencies]
glwn = { path = "../../graphics/glwn" }
math = { path = "../../math" }
gl = "0.14.0"
log = "0.4"
env_logger = "0.11" 

[dev-dependencies]
imagine = "0.5.3"
